name: Test Custom Lint Action

on:
  push:
    branches: [ main ]

jobs:
  test-verilator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 🚨 THIS IS THE MAGIC LINE! 🚨
      # Here you are calling the tool you just built!
      - name: Run My Custom Verilator Action
        id: my_linter
        uses: eswarnathjeyaramk/verilator-lint-action@v1
        with:
          files: 'good.sv bad.sv'
          severity: 'error'

      # Print the results so we can see the JSON output
      - name: View Results
        if: always() # Run this even if the linter fails
        run: |
          echo "My Custom Action produced the following JSON output:"
          echo '${{ steps.my_linter.outputs.results }}'
